PP-32 : Employee Module
techuz/project-planner-react pull request #33
Opened 2023-03-31 12:04 UTC by sanjay-techuz

2023-03-31 12:06 UTC, sanjay-techuz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Employee Module](https://trello.com/c/4xzYohmz/32-employee-module)

2023-04-03 10:22 UTC, ketanp-techuz commented on src/components/Form/Employee/EditEmployee.jsx
> +  const getSkills = async () => {
Make it common Fn, as we need it to multiple place

2023-04-03 10:23 UTC, ketanp-techuz commented on src/components/Table/Employee/List/EmployeeNameCell.jsx
> +          src={image}
I think we don't have avatar of users

2023-04-03 11:33 UTC, sanjay-techuz commented on src/components/Form/Employee/EditEmployee.jsx
> +  const getSkills = async () => {
This is done in next pr PP-37

2023-04-03 11:33 UTC, sanjay-techuz commented on src/components/Table/Employee/List/EmployeeNameCell.jsx
> +          src={image}
This is done in next pr PP-37

2023-04-04 04:32 UTC, ketanp-techuz approved these changes

2023-04-04 07:21 UTC, ashishtechuz requested changes

2023-04-04 07:21 UTC, ashishtechuz commented on src/components/Form/Employee/CreateEmployee.jsx
> +      values['status'] = values.status ? 'Active' : 'Inactive';
This seems unnecessary complexity. Please optimize this one.

2023-04-04 07:21 UTC, ashishtechuz commented on src/components/Form/Employee/EditEmployee.jsx
> +      formik.initialValues.status = data.status === 'Active' ? true : false;
Find a better way to handle this. since we are using formik. this one can surely optimized.

2023-04-04 07:21 UTC, ashishtechuz commented on src/components/Form/Employee/EditEmployee.jsx
> +      values['status'] = values.status ? 'Active' : 'Inactive';
Same as above comment

2023-04-04 07:21 UTC, ashishtechuz commented on src/components/Table/Employee/List/EmployeeNameCell.jsx
> +          src={image}
Thing is that we are not going to use Image at all. The circle will have the First Letter of user's name. No Avatar needed?

2023-04-04 07:21 UTC, ashishtechuz commented on src/components/Table/Employee/List/ProjectListCell.jsx
> +          if (totalHours) setAnchorEl(event.currentTarget);
Always use brackets for if condition.

2023-04-04 07:21 UTC, ashishtechuz commented on src/components/Table/Employee/List/index.jsx
> +      });
I suggest you make some sort of custom hook that can be reused across the app. I see this function is used at multiple places and taking more lines than 1 toast message should. Optimize.

2023-04-04 07:21 UTC, ashishtechuz commented on src/components/Table/Employee/List/index.jsx
> +      });
Fix it everywhere.

2023-04-04 12:04 UTC, sanjay-techuz commented on src/components/Form/Employee/CreateEmployee.jsx
> +      values['status'] = values.status ? 'Active' : 'Inactive';
i tried to optimize this code. but for that we have to change in lots of code.

2023-04-05 06:43 UTC, ashishtechuz commented on src/components/Form/Employee/CreateEmployee.jsx
> +      values['status'] = values.status ? 'Active' : 'Inactive';
Still why do we need these much of logic and lodash when we can simply use Array.map and can achieve the same? @ketanp-techuz @sanjay-techuz

2023-04-05 06:45 UTC, ashishtechuz commented on src/components/Form/Employee/CreateEmployee.jsx
> +      values['status'] = values.status ? 'Active' : 'Inactive';
We will go for lodash when our builtin array function can't perform this easily.

2023-04-05 11:36 UTC, ashishtechuz commented
@sanjay-techuz Resolve conflicts and we are good to go.

2023-04-05 12:35 UTC, ashishtechuz approved these changes

2023-04-06 05:10 UTC, merged