PP-65 : Add delete apis
techuz/project-planner-react pull request #49
Opened 2023-04-19 06:39 UTC by sanjay-techuz

2023-04-19 08:44 UTC, ketanp-techuz requested changes

2023-04-19 08:44 UTC, ketanp-techuz commented on src/components/Table/Project/DocumnetsAndLinks/index.jsx
> +  const isEnabled = getIsFeatureEnabled('DOCUMENTS', user?.loginDetails?.role);
Here you have to get the role from project, check milestone I've done it there

2023-04-19 08:44 UTC, ketanp-techuz commented on src/components/Table/Project/List/index.jsx
> +  const isEnabled = getIsFeatureEnabled('PROJECT', user?.loginDetails?.role);
same here

2023-04-19 10:27 UTC, ketanp-techuz approved these changes

2023-04-20 05:24 UTC, sanjay-techuz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add delete apis](https://trello.com/c/VfhKmzRr/65-add-delete-apis)

2023-04-20 12:53 UTC, ketanp-techuz approved these changes

2023-04-20 12:53 UTC, merged