Added formik with Yup and implemented in login
techuz/project-planner-react pull request #6
Opened 2023-02-28 10:12 UTC by ketanp-techuz

2023-02-28 10:28 UTC, ashishtechuz commented
Please fix eslint warnings to let deployment happen. Any warning while generating a build will fail the deployment.

2023-02-28 10:33 UTC, ketanp-techuz commented
> Please fix eslint warnings to let deployment happen. Any warning while generating a build will fail the deployment.

Fixed, warning because of it's not sync with master.

2023-02-28 11:17 UTC, ashishtechuz requested changes

2023-02-28 11:17 UTC, ashishtechuz commented on src/pages/Login/Login.jsx
> +      console.log("values", values);
Please remove console log after testing.

2023-02-28 12:11 UTC, ashishtechuz approved these changes

2023-02-28 12:11 UTC, merged

2023-03-03 05:44 UTC, ketanp-techuz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Added formik with Yup and implemented in login](https://trello.com/c/qvvZsanP/6-added-formik-with-yup-and-implemented-in-login)